# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - polars
    - pyarrow
    - pydantic
    - chromadb
    - ipykernel
    - python-dotenv
    - ruff
    - black
